---

name: Publish Docker image to Github Container Registry

env:
  image: rhythmictech/docker-atlantis-custom

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Github Container Registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.image }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags:  ${{ steps.meta.outputs.tags }}
