---

name: Publish Docker image to Github Container Registry

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Github Container Registry
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

## TODO use GITHUB_TOKEN once Github add support
## see https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/rhythmictech/graylog-integrations-plugin:latest
            ghcr.io/rhythmictech/graylog-integrations-plugin:${{ github.sha }}
