---

name: Publish Docker image to Github Packages

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/rhythmictech/graylog-integrations-plugin:latest
            ghcr.io/rhythmictech/graylog-integrations-plugin:${{ github.sha }}
